%include 'commands\about\command.asm'
%include 'commands\exit\command.asm'
%include 'commands\reboot\command.asm'
%include 'commands\version\command.asm'
%include 'commands\print\command.asm'
%include 'commands\shutdown\command.asm'
