%include 'command\nocommand.asm'
%include 'command\ls.asm'
%include 'command\about.asm'
%include 'command\echo.asm'
%include 'command\reboot.asm'
%include 'command\version.asm'
%include 'command\shutdown.asm'
%include 'command\exit.asm'
